"""Generate docs/course-index.md from the curriculum data.

Run:  uv run python scripts/course_index.py
      uv run python scripts/course_index.py --check   # CI: fail if it is stale

TRANSPORT ONLY. The schedule lives in `bootcamp_agent.curriculum` and the
exercise ids live in `bootcamp_agent.checks`. This file renders them, so the
day-by-day table cannot drift from the code that runs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bootcamp_agent.curriculum import (  # noqa: E402
    CHAPTERS,
    WEEK0_COURSES,
    WEEK0_UNITS,
    WEEK_TITLES,
    exercise_ids,
    unit_exercise_ids,
)

OUTPUT = ROOT / "docs" / "course-index.md"


def render() -> str:
    lines = [
        "<!-- generated by scripts/course_index.py — edit the curriculum module, not this file -->",
        "",
        "# Course index",
        "",
        "Fifteen sessions, Monday to Friday, two hours each. Every chapter folder holds",
        "a README (the session guide), `slides.md`, an exercise `notebook.ipynb` and a",
        "`solutions/notebook.ipynb`. Demo day has no notebook.",
        "",
        "**Checks** is how many exercises that chapter's notebook scores. Run one with",
        "`uv run bootcamp check ch03`, or all of them with `uv run bootcamp progress`.",
        "",
    ]
    lines += [
        "## Week 0: the prerequisite",
        "",
        f"Self-paced, before Monday 14 September. {len(WEEK0_UNITS)} units, all offline.",
        "No date: these are done when you do them.",
        "Short on time? The fast lane is the floor session 1 assumes; the courses",
        "beside it are the long form.",
        "",
    ]
    for course in WEEK0_COURSES:
        lines += [f"### {course}", "", "| # | Unit | Checks |", "|---|---|---|"]
        for unit in WEEK0_UNITS:
            if unit.course != course:
                continue
            lines.append(
                f"| {unit.number} | [{unit.title}]({unit.directory.relative_to(ROOT)}/) | "
                f"{len(unit_exercise_ids(unit.prefix))} |"
            )
        lines.append("")

    for module in sorted(WEEK_TITLES):
        chapters = [chapter for chapter in CHAPTERS if chapter.module == module]
        first, last = chapters[0], chapters[-1]
        lines += [
            f"## Week {module}: {WEEK_TITLES[module]}",
            "",
            f"{first.weekday} to {last.weekday}",
            "",
            "| Day | # | Session | Checks | Runs unattended |",
            "|---|---|---|---|---|",
        ]
        for chapter in chapters:
            checks = len(exercise_ids(chapter.chapter_id))
            if not chapter.has_notebook:
                unattended = "no notebook"
            elif chapter.manual_reason:
                unattended = f"no: {chapter.manual_reason}"
            else:
                unattended = "yes"
            lines.append(
                f"| {chapter.weekday} | {chapter.number} | "
                f"[{chapter.title}]({chapter.directory.relative_to(ROOT)}/) | "
                f"{checks or '—'} | {unattended} |"
            )
        lines.append("")
    runnable = sum(1 for chapter in CHAPTERS if chapter.runs_in_ci)
    total_checks = sum(len(exercise_ids(chapter.chapter_id)) for chapter in CHAPTERS)
    lines += [
        "## Totals",
        "",
        f"- {len(WEEK0_UNITS)} week-0 units, then {len(CHAPTERS)} sessions, "
        f"{runnable} of them running unattended in CI.",
        f"- {total_checks} scored exercises across the course.",
        "- Three chapters need a human or a hosted surface, and each says which in the",
        "  table above. That is a property of the lesson, not a gap in the tooling.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from what would be generated",
    )
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it:", file=sys.stderr)
            print("  uv run python scripts/course_index.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
